USE ROLE ACCOUNTADMIN;

USE SNOWFLAKE;

SELECT * FROM ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY;

SELECT DATE_TRUNC('DAY',START_TIME),SUM(CREDITS_USED) AS CREDITS_USED FROM ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
GROUP BY 1;


-- find average database usage trend for each day
SELECT USAGE_DATE, DATABASE_NAME,AVG(AVERAGE_DATABASE_BYTES),SUM(AVERAGE_FAILSAFE_BYTES) FROM ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
GROUP BY 1,2
ORDER BY 2,1 ASC;

-- find overall average database usage
SELECT DATABASE_NAME,AVG(AVERAGE_DATABASE_BYTES),SUM(AVERAGE_FAILSAFE_BYTES) FROM ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
GROUP BY 1;

-- find current table sizes
SELECT TABLE_CATALOG, TABLE_NAME, SUM(ACTIVE_BYTES), SUM(TIME_TRAVEL_BYTES), SUM(FAILSAFE_BYTES) FROM ACCOUNT_USAGE.TABLE_STORAGE_METRICS
GROUP BY 1,2;


-- 1) enable time travel
-- 2) add additional data into table to force a change in size
-- 3) update existing data to view time travel usage
-- 4) check again

-- set time travel retention to 1 days
USE ROLE ACCOUNTADMIN;
SET DATA_RETENTION_TIME_IN_DAYS = 1;


-- add large number of rows in the transactions table
-- I have also randomized the data other wise column compression
-- will result in negligible rise in the storage
INSERT INTO TRANSACTIONS 
SELECT a.Transaction_Date + MOD(RANDOM(), 2000), RANDOM(), a.Customer_ID,a.Amount 
FROM transactions a CROSS JOIN transactions b CROSS JOIN transactions c;

-- find average database usage trend for each day
SELECT USAGE_DATE, DATABASE_NAME,AVG(AVERAGE_DATABASE_BYTES),SUM(AVERAGE_FAILSAFE_BYTES) FROM ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
GROUP BY 1,2
ORDER BY 2,1 ASC;

-- find overall average database usage
SELECT DATABASE_NAME,AVG(AVERAGE_DATABASE_BYTES),SUM(AVERAGE_FAILSAFE_BYTES) FROM ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
GROUP BY 1;

-- find current table sizes
SELECT TABLE_CATALOG, TABLE_NAME, SUM(ACTIVE_BYTES), SUM(TIME_TRAVEL_BYTES), SUM(FAILSAFE_BYTES) FROM ACCOUNT_USAGE.TABLE_STORAGE_METRICS
GROUP BY 1,2;
