CREATE USER jake PASSWORD = 'doe' DEFAULT_ROLE = ACCOUNTADMIN MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE ACCOUNTADMIN TO USER jake;

CREATE USER john PASSWORD = 'doe' DEFAULT_ROLE = SECURITYADMIN MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SECURITYADMIN TO USER john;

CREATE USER jane PASSWORD = 'doe' DEFAULT_ROLE = SYSADMIN MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE SYSADMIN TO USER jane;




