

GRANT ALL ON FUTURE SCHEMAS IN DATABASE MARKETING_DATABASE TO ROLE MARKETING_DBA WITH GRANT OPTION;
GRANT ALL ON FUTURE TABLES IN SCHEMA MARKETING_DATABASE.PUBLIC TO ROLE MARKETING_DBA WITH GRANT OPTION;
